### ISSUE TITLE
After upgrade php to PHP 5.6.12 get notice

### ISSUE THREAD

**Issue by TomasPilaru** [Zenify/DoctrineBehaviors#7]
Hi Tom,
today I updated my PHP to 5.6.12 and after upgrade app throws this php notice:
![notice](https://cloud.githubusercontent.com/assets/8326937/9755514/d94f3f64-56d2-11e5-8ef4-133e18a4836f.png)

Problem was a ampersand in __get method. Why this method must return reference? If i remove ampersand from declaration app works fine.

Thanks

**Comment by TomasVotruba** [comment]
Hi, I think there was some issue with `Nette\Object`.

Could you try to extend your entity from it and confirm it works?

**Comment by TomasPilaru** [comment]
I found solution see #8 . I removed this principle in #5 ... 
Sorry for that!
